# Generated by Django 5.0.2 on 2024-05-16 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Спецификация заказа',
                'verbose_name_plural': 'Спецификации заказов',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заявки')),
                ('chosen_date', models.DateField(verbose_name='Дата выбранная пользователем')),
                ('chosen_time', models.TimeField(null=True, verbose_name='Время выбранное пользователем')),
                ('desired_service', models.CharField(blank=True, max_length=150, null=True, verbose_name='Статус выполнения')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий клиента')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает выполнения'), ('WAITING_CAR', 'Ожидает автомобиля'), ('IN_PROGRESS', 'В процессе выполнения'), ('COMPLETED', 'Выполнен')], default='PENDING', max_length=20, verbose_name='Статус выполнения')),
                ('final_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Конечная стоимость')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания выполнения')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Время окончания выполнения')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_app.car', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
