# Generated by Django 5.0.2 on 2024-05-11 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule_app', '0001_initial'),
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanicschedule',
            name='mechanic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users_app.mechanic', verbose_name='Идентификатор менеджера'),
        ),
        migrations.AddField(
            model_name='mechanicschedule',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule_app.shift'),
        ),
    ]
