# Generated by Django 5.0.2 on 2024-05-16 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule_app', '0001_initial'),
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanicschedule',
            name='mechanic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users_app.mechanic', verbose_name='Идентификатор механика'),
        ),
        migrations.AddField(
            model_name='mechanicschedule',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule_app.shift'),
        ),
        migrations.AddField(
            model_name='week',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule_app.month'),
        ),
        migrations.AddField(
            model_name='mechanicschedule',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule_app.week'),
        ),
        migrations.AddField(
            model_name='mechanicschedule',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule_app.weekday'),
        ),
        migrations.AddField(
            model_name='week',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule_app.year'),
        ),
        migrations.AddField(
            model_name='month',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule_app.year'),
        ),
        migrations.AddField(
            model_name='mechanicschedule',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule_app.year'),
        ),
    ]
