# Generated by Django 5.0.2 on 2024-05-18 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mechanicschedule',
            name='year',
        ),
    ]
