# Generated by Django 5.0.2 on 2024-05-18 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0004_remove_mechanicschedule_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='month',
            name='year',
        ),
        migrations.RemoveField(
            model_name='week',
            name='month',
        ),
        migrations.RemoveField(
            model_name='week',
            name='year',
        ),
        migrations.DeleteModel(
            name='WeekDay',
        ),
        migrations.AddField(
            model_name='shift',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=111),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mechanicschedule',
            name='mechanic',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='schedule_app.mechanic'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='mechanicschedule',
            unique_together={('date', 'shift', 'mechanic')},
        ),
        migrations.DeleteModel(
            name='Month',
        ),
        migrations.DeleteModel(
            name='Week',
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
