# Generated by Django 5.0.2 on 2024-05-18 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0005_mechanic_remove_month_year_remove_week_month_and_more'),
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanicschedule',
            name='mechanic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.mechanic'),
        ),
        migrations.DeleteModel(
            name='Mechanic',
        ),
    ]
