# Generated by Django 5.0.2 on 2024-05-11 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0001_initial'),
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mechanicspecialization',
            name='service',
        ),
        migrations.AddField(
            model_name='mechanicspecialization',
            name='service_group',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='services_app.servicegroup', verbose_name='Группа услуг'),
            preserve_default=False,
        ),
    ]
