# Generated by Django 5.0.2 on 2024-02-20 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AuthenticationApp', '0001_initial'),
        ('CarApp', '0001_initial'),
        ('ServiceApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает выполнения'), ('IN_PROGRESS', 'В процессе выполнения'), ('COMPLETED', 'Выполнен')], default='PENDING', max_length=20, verbose_name='Статус выполнения')),
                ('final_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Конечная стоимость')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала выполнения')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания выполнения')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Время начала выполнения')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Время окончания выполнения')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarApp.car', verbose_name='Автомобиль')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AuthenticationApp.manager', verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthenticationApp.mechanic', verbose_name='Механик')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrdersApp.order', verbose_name='Заказ')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceApp.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Спецификация заказа',
                'verbose_name_plural': 'Спецификации заказов',
            },
        ),
    ]
