# Generated by Django 5.0.2 on 2024-02-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
