# Generated by Django 5.0.2 on 2024-02-21 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0001_initial'),
        ('OrdersApp', '0002_remove_order_manager_appeal_order_appeal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='manager_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AuthenticationApp.manager', verbose_name='Идентификатор менеджера'),
        ),
    ]
