# Generated by Django 5.0.2 on 2024-02-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersApp', '0002_appeal_is_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='final_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Конечная стоимость'),
        ),
    ]
