# Generated by Django 5.0.2 on 2024-05-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sts', models.CharField(max_length=100, verbose_name='СТС')),
                ('brand', models.CharField(max_length=100, verbose_name='Марка')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('body_type', models.CharField(max_length=100, verbose_name='Тип кузова')),
                ('license_plate', models.CharField(max_length=20, verbose_name='Государственный номер')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('vin_number', models.CharField(max_length=100, verbose_name='VIN номер')),
                ('year_of_manufacture', models.PositiveSmallIntegerField(verbose_name='Год выпуска')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200, verbose_name='Комментарий')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Рекомендация',
                'verbose_name_plural': 'Рекомендации',
            },
        ),
    ]
