# Generated by Django 5.0.2 on 2024-02-24 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='price_range',
            new_name='price',
        ),
    ]
