# Generated by Django 5.0.2 on 2024-02-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(max_length=11, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
