# Generated by Django 5.0.2 on 2024-02-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0002_alter_client_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.EmailField(max_length=100, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
