# Generated by Django 5.0.2 on 2024-06-07 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='duration',
        ),
    ]
